### ISSUE TITLE
google-cloud-trace-1.1.0 is not compatible with opencensus-0.7.11 opencensus-ext-stackdriver-0.7.4

### ISSUE THREAD

**Issue by hilliao** [googleapis/python-trace#59]
with a new python virtual environment, installing opencensus opencensus-ext-stackdriver google-cloud-trace  grpcio causes 
`from opencensus.ext.stackdriver import trace_exporter as stackdriver_exporter` to fail; when will google-cloud-trace 1.1.0 be compatible with others as the ERROR below shows?

```
$ pip install opencensus opencensus-ext-stackdriver google-cloud-trace
 pip install opencensus opencensus-ext-stackdriver google-cloud-trace
Collecting opencensus
  Using cached opencensus-0.7.11-py2.py3-none-any.whl (127 kB)
Collecting opencensus-ext-stackdriver
  Using cached opencensus_ext_stackdriver-0.7.4-py2.py3-none-any.whl (12 kB)
Collecting google-cloud-trace
  Using cached google_cloud_trace-1.1.0-py2.py3-none-any.whl (67 kB)
Collecting opencensus-context==0.1.2
  Using cached opencensus_context-0.1.2-py2.py3-none-any.whl (4.4 kB)
Collecting google-api-core<2.0.0,>=1.0.0
  Downloading google_api_core-1.24.1-py2.py3-none-any.whl (92 kB)
     |████████████████████████████████| 92 kB 3.2 MB/s 
Collecting google-cloud-monitoring<1.0.0,>=0.30.0
  Using cached google_cloud_monitoring-0.36.0-py2.py3-none-any.whl (235 kB)
Collecting proto-plus>=1.4.0
  Using cached proto-plus-1.13.0.tar.gz (44 kB)
Collecting requests<3.0.0dev,>=2.18.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 3.0 MB/s 
Collecting protobuf>=3.12.0
  Using cached protobuf-3.14.0-cp38-cp38-manylinux1_x86_64.whl (1.0 MB)
Collecting google-auth<2.0dev,>=1.21.1
  Using cached google_auth-1.24.0-py2.py3-none-any.whl (114 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Using cached googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Collecting pytz
  Using cached pytz-2020.4-py2.py3-none-any.whl (509 kB)
Requirement already satisfied: setuptools>=34.0.0 in ./py-test/lib/python3.8/site-packages (from google-api-core<2.0.0,>=1.0.0->opencensus) (44.0.0)
Collecting six>=1.13.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 18.4 MB/s 
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.6"
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.0-py3-none-any.whl (12 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Building wheels for collected packages: proto-plus
  Building wheel for proto-plus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hil/tmp/py-test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7k6_r9xg/proto-plus/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7k6_r9xg/proto-plus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6a4ru40u
       cwd: /tmp/pip-install-7k6_r9xg/proto-plus/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for proto-plus
  Running setup.py clean for proto-plus
Failed to build proto-plus
ERROR: opencensus-ext-stackdriver 0.7.4 has requirement google-cloud-trace<1.0.0,>=0.20.0, but you'll have google-cloud-trace 1.1.0 which is incompatible.
Installing collected packages: opencensus-context, chardet, certifi, urllib3, idna, requests, six, protobuf, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, googleapis-common-protos, pytz, google-api-core, opencensus, proto-plus, google-cloud-trace, google-cloud-monitoring, opencensus-ext-stackdriver
    Running setup.py install for proto-plus ... done
Successfully installed cachetools-4.2.0 certifi-2020.12.5 chardet-4.0.0 google-api-core-1.24.1 google-auth-1.24.0 google-cloud-monitoring-0.36.0 google-cloud-trace-1.1.0 googleapis-common-protos-1.52.0 idna-2.10 opencensus-0.7.11 opencensus-context-0.1.2 opencensus-ext-stackdriver-0.7.4 proto-plus-1.13.0 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pytz-2020.4 requests-2.25.1 rsa-4.6 six-1.15.0 urllib3-1.26.2

$ pip install grpcio
Collecting grpcio
  Using cached grpcio-1.34.0-cp38-cp38-manylinux2014_x86_64.whl (4.0 MB)
Requirement already satisfied: six>=1.5.2 in ./py-test/lib/python3.8/site-packages (from grpcio) (1.15.0)
Installing collected packages: grpcio
Successfully installed grpcio-1.34.0


$ python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opencensus.trace.tracer
>>> from opencensus.ext.stackdriver import trace_exporter as stackdriver_exporter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hil/tmp/py-test/lib/python3.8/site-packages/opencensus/ext/stackdriver/trace_exporter/__init__.py", line 18, in <module>
    from google.cloud.trace.client import Client
ModuleNotFoundError: No module named 'google.cloud.trace.client'
```

**Comment by busunkim96** [comment]
Hi @hilliao,

In this case the opencensus-ext-stackdriver package is higher in the stack. They will need to update their library to support `google-cloud-trace>1.0.0`

https://github.com/census-instrumentation/opencensus-python/issues/954
